DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS MESSAGE;



CREATE TABLE CONTACT (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , FIRST_NAME VARCHAR(99) NOT NULL
     , LAST_NAME VARCHAR(99) NOT NULL
     , BIRTH_DATE DATE
);

CREATE TABLE HOBBY (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , TITLE VARCHAR(99) NOT NULL
     , DESCRIPTION VARCHAR (99) NOT NULL
     , CONTACT_ID INT NOT NULL
);


CREATE TABLE PLACE (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , TITLE VARCHAR(99) NOT NULL
     , DESCRIPTION VARCHAR (99) NOT NULL
	 , LONGITUDE DOUBLE
	 , LATITUDE DOUBLE
	 , CONTACT_ID INT NOT NULL
);

CREATE TABLE MESSAGE (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , CONTACTFROM VARCHAR(99) NOT NULL
     , CONTACTTO VARCHAR (99) NOT NULL
	 , CONTENT VARCHAR(250)
	 , DATE_MESS DATE NOT NULL
	 , CONTACT_ID INT NOT NULL
);


