DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CONTACT_HOBBY;
DROP TABLE IF EXISTS CONTACT_PLACE;
DROP TABLE IF EXISTS CONTACT_FRIENDSHIP;
DROP TABLE IF EXISTS CONTACT_DETAIL;


CREATE TABLE CONTACT (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , FIRST_NAME VARCHAR(99) NOT NULL
     , LAST_NAME VARCHAR(99) NOT NULL
     , BIRTH_DATE DATE
);

CREATE TABLE HOBBY (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , CONTACT_ID INT
     , TITLE VARCHAR(99) NOT NULL
     , DESCRIPTION VARCHAR (99) NOT NULL
);

CREATE TABLE CONTACT_HOBBY(
        CONTACT_ID INT NOT NULL
      , HOBBY_ID INT NOT NULL
);

CREATE TABLE PLACE (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , CONTACT_ID INT
     , TITLE VARCHAR(99) NOT NULL
     , DESCRIPTION VARCHAR (99) NOT NULL
	 , LONGITUDE DOUBLE
	 , LATITUDE DOUBLE

);

CREATE TABLE CONTACT_PLACE(
        CONTACT_ID INT NOT NULL
      , PLACE_ID INT NOT NULL
);

CREATE TABLE MESSAGE (
       ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
     , CONTACTFROM VARCHAR(99) NOT NULL
     , CONTACTTO VARCHAR (99) NOT NULL
	 , CONTENT VARCHAR(250)
	 , DATE_MESS DATE NOT NULL

);

CREATE TABLE CONTACT_FRIENDSHIP(
        CONTACT_ID INT NOT NULL
      , FRIEND_ID INT NOT NULL
);

CREATE TABLE CONTACT_DETAIL(

);

